version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    insecure-external-code-execution: allow
    open-pull-requests-limit: 5

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    insecure-external-code-execution: allow
    open-pull-requests-limit: 5 

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
