services:
  api:
    image: ai-assistant
    build: .
    ports:
      - "8080:8080"
    command:
      - "uvicorn"
      - "ai_assistant.api.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8080"
      - "--reload"
    environment:
      - DATABASE_HOST=db
    env_file: .env
    restart: on-failure
  
  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ai_assistant
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: