
volumes:
  pg_data:

services:
  api:
    image: ai-assistant
    build: .
    secrets:
      - GCP_TOKEN
    ports:
      - "8080:8080"
    command:
      - "uvicorn"
      - "ai_assistant.api.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8080"
      - "--reload"
    environment:
      - DATABASE_HOST=db
    env_file: .env
    restart: on-failure
    volumes:
      - .:/home/worker/app
      - ~/.config/gcloud:/home/worker/.config/gcloud
  
  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ai_assistant
    volumes:
      - pg_data:/var/lib/postgresql/data

secrets:
  GCP_TOKEN:
    environment: "GCP_TOKEN"
